name: Build and Test .NET Web App

on:
  push:
    branches: [ "main" ]  # Change to "master" if your default branch is master

jobs:
  build:

    runs-on: ubuntu-latest  # Use Ubuntu runner

    steps:
    - uses: actions/checkout@v3  # Checks out your code

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x  # Target .NET 9.0
        include-prerelease: true  # Ensures preview versions like .NET 9 are included

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal
